export * from './not-allowed-error'
export * from './resource-not-found-error'
export * from './duplicate-resource-found-error'
export * from './student-already-exists-error'
export * from './wrong-credentials-error'
